# Generated by Django 3.1.7 on 2021-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(default='', max_length=35),
        ),
    ]
